# Global - Settings which persist for every other section
# ======================================================
Global:
    github_token: # token for GitHub, can be acquired from: https://github.com/settings/tokens

# Launcher - Defines the to be launched Application with optional args
# ====================================================================
Launcher:
    filename: NorthstarLauncher.exe  # launches the NorthstarLauncher
#    filename: Titanfall2.exe  # launches Vanilla Titanfall2
#    argumnets: ''  # Arguments for the launcher. The NorthstarLauncher uses also the args defined in the ns_startup_args.txt file

# Manager - Config for the Manager of Northstar
# =============================================
Manager:
    repository: FromWau/NorthstarManager  # repo from where to search for updates. Will search at first at GitHub.com and then at northstar.thunderstore.io
    last_update: '0001-01-01T00:00:00'  # publishe date of the latest version of the repo
    file: NorthstarManager.exe  # main file of the repo
#    install_dir: .  # install directory
#    ignore_updates: true  # will ignore new version and keeps the installed version
#    ignore_prerelease: true  # will ignore pre_releases when searching for new realeses of the repo

# Mods - List of managed mods
# ===========================
Mods:
    Northstar:  # Northstar will be handled here
        repository: R2Northstar/Northstar  # repo of Northstar
        last_update: '0001-01-01T00:00:00'  # publishe date of the latest version of Northstar
        install_dir: .  # install directory is necessary for Northstar default is in the mods folder
        file: NorthstarLauncher.exe  # main file of the repo
        exclude_files:  # files that should be excluded when updating the repo
        - ns_startup_args.txt
        - ns_startup_args_dedi.txt


#    How to install a new mod (example for SpeedOMeter) :
#    -------------------------
#    S2speedometer:  # Name of Mod (could be anything)
#        repository: Mysterious_Reuploads/S2speedometer  # the repo from where to grab the latest release

# Servers - List of all Servers that should be managed
# ====================================================
#Servers:
#    enabled: false  # disables all listed servers for update checks, and they will not get launched
#
#    How to install/ configure a server (you do not need to download or setup anything just configure what you want down below) (example for Kraber9k Server):
#    -----------------------------------
#    Kraber 9k:  # Name of the Server
#        dir: servers/Kraber 9k  # directory where the server is located
#        enabled: false  # disables this server for update checks, and the server will not get launched
#        Mods:  # Mods for the server
#            Northstar:  # Northstar, is needed for the server
#                repository: R2Northstar/Northstar  # repo of Northstar
#                last_update: '0001-01-01T00:00:00'  # publishe date of the latest version of Northstar
#                install_dir: .  # install directory from the root dir of the server
#                file: NorthstarLauncher.exe  # main file of the repo
#
#        config:  # Config of the Server, configuration for servers is split up into 3 different files
#            ns_startup_args_dedi.txt: +mp_gamemode ps +setplaylistvaroverride "custom_air_acc_pilot 9000" +setplaylist private_match  # startup args for this server
#            mod.json:  # config for Northstar.CustomServers
#                ConVars:  # the section of the file
#                    ns_private_match_last_map: mp_glitch  # key and value of a configuration
#                    ns_private_match_last_mode: ps
#                    ns_disallowed_weapons: mp_weapon_r97,mp_weapon_alternator_smg,mp_weapon_car,mp_weapon_hemlok_smg,mp_weapon_lmg,mp_weapon_lstar,mp_weapon_esaw,mp_weapon_rspn101,mp_weapon_vinson,mp_weapon_hemlok,mp_weapon_g2,mp_weapon_shotgun,mp_weapon_mastiff,mp_weapon_dmr,mp_weapon_doubletake,mp_weapon_epg,mp_weapon_smr,mp_weapon_pulse_lmg,mp_weapon_softball,mp_weapon_autopistol,mp_weapon_semipistol,mp_weapon_wingman,mp_weapon_shotgun_pistol,mp_weapon_rocket_launcher,mp_weapon_arc_launcher,mp_weapon_defender,mp_weapon_mgl,mp_weapon_wingman_n,mp_weapon_rspn101_og
#                    ns_disallowed_weapon_primary_replacement: mp_weapon_sniper
#            autoexec_ns_server.cfg:  # config for server
#                ns_server_name: Example Kraber9k Server  # key and value of a configuration
#                ns_server_desc: Example Server configurated via FromWau/NorthstarManager
#                ns_should_return_to_lobby: 1
#                ns_private_match_only_host_can_change_settings: 2
#                ns_player_auth_port: 8081  # IMPORTANT: EVERY RUNNING SERVER NEEDS AN UNIQUE PORT AND THIS PORT NEEDS TO BE PORT-FORWARDED
