# Global - Settings which persist for every other section
# =======================================================
Global:
    github_token:  # Token for GitHub, can be acquired from: https://github.com/settings/tokens
#    log_level: DEBUG  # Sets the log level. Can be set to CRITICAL, ERROR, WARNING, INFO, DEBUG. Default is INFO

# Launcher - Defines the to be launched Application with optional args
# ====================================================================
Launcher:
    filename: NorthstarLauncher.exe  # launches the NorthstarLauncher
#    filename: Titanfall2.exe  # launches Vanilla Titanfall2
    argumnets: ''  # Arguments for the launcher. Arguments in this file will replace if already existing those in the 'ns_startup_args.txt'

# Manager - Config for the Manager of Northstar
# =============================================
Manager:
    repository: FromWau/NorthstarManager  # repo from where to search for updates. Will search at first at GitHub.com and then at northstar.thunderstore.io
    last_update: '0001-01-01T00:00:00'  # publishe date of the latest version of the repo
    file: NorthstarManager.exe  # main file of the repo
#    install_dir: .  # install directory
#    ignore_updates: true  # will ignore new version and keeps the installed version
#    ignore_prerelease: true  # will ignore pre_releases when searching for new realeses of the repo

# Mods - List of managed mods
# ===========================
Mods:
    Northstar:  # Northstar will be handled here
        repository: R2Northstar/Northstar  # repo of Northstar
        last_update: '0001-01-01T00:00:00'  # publishe date of the latest version of Northstar
        install_dir: .  # install directory is necessary for Northstar default is in the mods folder
        file: NorthstarLauncher.exe  # main file of the repo
        exclude_files:  # files that should be excluded when updating the repo
        - ns_startup_args.txt
        - ns_startup_args_dedi.txt


#    How to install a new mod (example for SpeedOMeter) :
#    -------------------------
#    S2speedometer:  # Name of Mod (could be anything)
#        repository: Mysterious_Reuploads/S2speedometer  # the repo from where to grab the latest release

# Servers - List of all Servers that should be managed
# ====================================================
Servers:
    enabled: false  # disables all listed servers for update checks, and they will not get launched
#
#    How to install/ configure a server (you do not need to download or setup anything just configure what you want down below) (example for Kraber9k Server):
#    -----------------------------------
    Kraber 9k:  # Name of the Server
#        dir: servers/Kraber 9k  # directory where the server is located. Default is the yaml path (Servers/Servername).
#        enabled: false  # disables this server for update checks, and the server will not get launched
        Mods:  # Mods for the server
            Northstar:  # Northstar, is needed for the server
                repository: R2Northstar/Northstar  # repo of Northstar
                last_update: '0001-01-01T00:00:00'  # publishe date of the latest version of Northstar
                install_dir: .  # install directory from the logger dir of the server
                file: NorthstarLauncher.exe  # main file of the repo
            
            PlayerVote:  # just nice to have
                repository: ScureX/PlayerVote
                last_update: '0001-01-01T00:00:00'
            
        config:  # Config of the Server, configuration for servers is split up into 3 different files
            ns_startup_args_dedi.txt: +setplaylist private_match -multiple +mp_gamemode ps +setplaylistvaroverrides "custom_air_accel_pilot 9000" -enablechathooks  # startup args for this server
            mod.json:  # config for Northstar.CustomServers
                ConVars:  # the section of the file
                    ns_private_match_last_map: mp_glitch  # key and value of a configuration
                    ns_private_match_last_mode: ps
                    ns_disallowed_weapons: mp_weapon_r97,mp_weapon_alternator_smg,mp_weapon_car,mp_weapon_hemlok_smg,mp_weapon_lmg,mp_weapon_lstar,mp_weapon_esaw,mp_weapon_rspn101,mp_weapon_vinson,mp_weapon_hemlok,mp_weapon_g2,mp_weapon_shotgun,mp_weapon_mastiff,mp_weapon_dmr,mp_weapon_doubletake,mp_weapon_epg,mp_weapon_smr,mp_weapon_pulse_lmg,mp_weapon_softball,mp_weapon_autopistol,mp_weapon_semipistol,mp_weapon_wingman,mp_weapon_shotgun_pistol,mp_weapon_rocket_launcher,mp_weapon_arc_launcher,mp_weapon_defender,mp_weapon_mgl,mp_weapon_wingman_n,mp_weapon_rspn101_og
                    ns_disallowed_weapon_primary_replacement: mp_weapon_sniper
            autoexec_ns_server.cfg:  # config for server
                ns_server_name: "[EU] Example Kraber9k Server"  # key and value of a configuration
                ns_server_desc: Example Server configurated via FromWau/NorthstarManager
                ns_should_return_to_lobby: 1
                ns_private_match_only_host_can_change_settings: 2
                ns_player_auth_port: 8081  # IMPORTANT: EVERY RUNNING SERVER NEEDS AN UNIQUE TCP PORT AND THIS PORT NEEDS TO BE PORT-FORWARDED IN YOUR ROUTER SETTINGS

# List of example server configurations:
# ======================================               
#     FlipSide:
#         enabled: false
#         Mods:
#             Northstar:
#                 repository: R2Northstar/Northstar
#                 install_dir: .
#                 file: NorthstarLauncher.exe
#                 last_update: '0001-01-01T00:00:00'
#             FlipSide_Mod:
#                 repository: The_Peepeepoopoo_man/FlipSide
#                 last_update: '0001-01-01T00:00:00'
#             PlayerVote:
#                 repository: ScureX/PlayerVote
#                 last_update: '0001-01-01T00:00:00'
#         config:
#             ns_startup_args_dedi.txt: +setplaylist private_match -multiple +mp_gamemode ffa -enablechathooks +setplaylistvaroverrides "custom_air_accel_pilot 9000 boosts_enabled 1 scorelimit 25 earn_meter_pilot_multiplier 0 Flipside 1 WallLocation 0 Smoke_wall 0"
#             mod.json:
#                 ConVars:
#                     ns_private_match_last_map: mp_glitch
#                     ns_private_match_last_mode: ffa
#             autoexec_ns_server.cfg:
#                 ns_server_name: Example FlipSide Server
#                 ns_server_desc: Example Server configurated via FromWau/NorthstarManager
#                 ns_should_return_to_lobby: 0
#                 ns_private_match_only_host_can_change_settings: 2
#                 ns_private_match_countdown_length: 0
#                 ns_player_auth_port: 8081
#                 pv_skip_enabled: 0
#                 pv_vote_map_enabled: 0
#                 pv_maps: mp_glitch
#                 
#     FlipSide_HoloShift:
#         enabled: false
#         Mods:
#             Northstar:
#                 repository: R2Northstar/Northstar
#                 install_dir: .
#                 file: NorthstarLauncher.exe
#                 last_update: '0001-01-01T00:00:00'
#             PlayerVote:
#                 repository: ScureX/PlayerVote
#                 last_update: '0001-01-01T00:00:00'
#             FlipSide_Mod:
#                 repository: The_Peepeepoopoo_man/FlipSide
#                 last_update: '0001-01-01T00:00:00'    
#             HoloShift_Mod:
#                 repository: Legonzaur/HoloShift
#                 last_update: '0001-01-01T00:00:00'
#         config:
#             ns_startup_args_dedi.txt: +setplaylist private_match -multiple +mp_gamemode ffa -enablechathooks +setplaylistvaroverrides "custom_air_accel_pilot 9000 boosts_enabled 1 scorelimit 25 earn_meter_pilot_multiplier 0 Flipside 1 WallLocation 1 Smoke_wall 0 featured_mode_all_holopilot 1"
#             mod.json:
#                 ConVars:
#                     ns_private_match_last_map: mp_glitch
#                     ns_private_match_last_mode: ffa
#             autoexec_ns_server.cfg:
#                 ns_server_name: "[EU/AT] FromWau's FlipSide+HoloShift"
#                 ns_server_desc: "Server runs Mods: FlipSide, HoloShift, PlayerVote. Game mode is FFA with 9k air accel and no Boosts/Titans. Server should auto restart after crashing."
#                 ns_should_return_to_lobby: 0
#                 ns_private_match_only_host_can_change_settings: 2
#                 ns_private_match_countdown_length: 0
#                 ns_player_auth_port: 8081
#                 pv_skip_enabled: 0
#                 pv_vote_map_enabled: 0
#                 pv_maps: mp_glitch
# 
#     Kraber9k:
#         enabled: false
#         Mods:
#             Northstar:
#                 repository: R2Northstar/Northstar
#                 last_update: '0001-01-01T00:00:00'
#                 install_dir: .
#                 file: NorthstarLauncher.exe
# 
#             PlayerVote:
#                 repository: ScureX/PlayerVote
#                 last_update: '0001-01-01T00:00:00'
#         config:
#             ns_startup_args_dedi.txt: +setplaylist private_match -multiple +mp_gamemode ps +setplaylistvaroverrides "custom_air_accel_pilot 9000" -enablechathooks
#             mod.json:
#                 ConVars:
#                     ns_private_match_last_map: mp_glitch
#                     ns_private_match_last_mode: ps
#                     ns_disallowed_weapons: mp_weapon_r97,mp_weapon_alternator_smg,mp_weapon_car,mp_weapon_hemlok_smg,mp_weapon_lmg,mp_weapon_lstar,mp_weapon_esaw,mp_weapon_rspn101,mp_weapon_vinson,mp_weapon_hemlok,mp_weapon_g2,mp_weapon_shotgun,mp_weapon_mastiff,mp_weapon_dmr,mp_weapon_doubletake,mp_weapon_epg,mp_weapon_smr,mp_weapon_pulse_lmg,mp_weapon_softball,mp_weapon_autopistol,mp_weapon_semipistol,mp_weapon_wingman,mp_weapon_shotgun_pistol,mp_weapon_rocket_launcher,mp_weapon_arc_launcher,mp_weapon_defender,mp_weapon_mgl,mp_weapon_wingman_n,mp_weapon_rspn101_og
#                     ns_disallowed_weapon_primary_replacement: mp_weapon_sniper
#             autoexec_ns_server.cfg:
#                 ns_server_name: "[EU/AT] FromWau's Kraber9k Server"
#                 ns_server_desc: Standard Kraber9k Server on Glitch. Server should auto restart after crashing.
#                 ns_should_return_to_lobby: 1
#                 ns_private_match_only_host_can_change_settings: 2
#                 ns_private_match_countdown_length: 0
#                 ns_player_auth_port: 8081
#                 pv_skip_enabled: 0
#                 pv_vote_map_enabled: 0
#                 pv_maps: mp_glitch
#     
#     
#     HarvesterBattle:
#         enabled: false
#         Mods:
#             Northstar:
#                 repository: R2Northstar/Northstar
#                 last_update: '0001-01-01T00:00:00'
#                 install_dir: .
#                 file: NorthstarLauncher.exe
# 
#             PlayerVote:
#                 repository: ScureX/PlayerVote
#                 last_update: '0001-01-01T00:00:00'
#             HarvesterBattle_Mod:
#                 repository: The_Peepeepoopoo_man/HarvesterBattle
#                 last_update: '0001-01-01T00:00:00'
#         config:
#             ns_startup_args_dedi.txt: +setplaylist private_match -multiple +mp_gamemode
#                 tdm +setplaylistvaroverrides "custom_air_accel_pilot 9000 HarvesterPush
#                 1 Harvester_health 6900" -enablechathooks
#             mod.json:
#                 ConVars:
#                     ns_private_match_last_map: mp_glitch
#                     ns_private_match_last_mode: tdm
#             autoexec_ns_server.cfg:
#                 ns_server_name: "[EU/AT] FromWau's HarvesterBattle Server"
#                 ns_server_desc: Example Server configurated via FromWau/NorthstarManager
#                 ns_should_return_to_lobby: 1
#                 ns_private_match_only_host_can_change_settings: 2
#                 ns_private_match_countdown_length: 0
#                 ns_player_auth_port: 8081
#                 pv_maps: mp_angel_city,mp_black_water_canal,mp_colony02,mp_complex3,mp_crashsite3,mp_drydock,mp_eden,mp_forwardbase_kodai,mp_glitch,mp_grave,mp_homestead,mp_thaw,mp_wargames
# 
#     Comp_CTF:
#         enabled: false
#         Mods:
#             Northstar:
#                 repository: R2Northstar/Northstar
#                 last_update: '0001-01-01T00:00:00'
#                 install_dir: .
#                 file: NorthstarLauncher.exe
# 
#             PlayerVote:
#                 repository: ScureX/PlayerVote
#                 last_update: '0001-01-01T00:00:00'
#         config:
#             ns_startup_args_dedi.txt: +setplaylist private_match -multiple +mp_gamemode
#                 ctf_comp -enablechathooks
#             mod.json:
#                 ConVars:
#                     ns_private_match_last_map: mp_glitch
#                     ns_private_match_last_mode: ctf_comp
#             autoexec_ns_server.cfg:
#                 ns_server_name: "[EU/AT] FromWau's Comp CTF Server"
#                 ns_server_desc: Example Server configurated via FromWau/NorthstarManager
#                 ns_should_return_to_lobby: 1
#                 ns_private_match_only_host_can_change_settings: 2
#                 ns_private_match_countdown_length: 0
#                 ns_player_auth_port: 8081
#                 pv_switch_enabled: 0
#                 pv_extend_vote_enabled: 0
# 
#     CrappyOddBall:
#         enabled: false
#         Mods:
#             Northstar:
#                 repository: R2Northstar/Northstar
#                 last_update: '0001-01-01T00:00:00'
#                 install_dir: .
#                 file: NorthstarLauncher.exe
# 
#             PlayerVote:
#                 repository: ScureX/PlayerVote
#                 last_update: '0001-01-01T00:00:00'
#             CrappyOddBall_Mod:
#                 repository: Palomar/CrappyOddBall
#                 last_update: '0001-01-01T00:00:00'
#         config:
#             ns_startup_args_dedi.txt: +setplaylist private_match -multiple +mp_gamemode
#                 ffa -enablechathooks +setplaylistvaroverrides "custom_air_accel_pilot
#                 9000 Oddball 1 Battery-Timeout 30 scorelimit 250"
#             mod.json:
#                 ConVars:
#                     ns_private_match_last_map: mp_glitch
#                     ns_private_match_last_mode: ffa
#             autoexec_ns_server.cfg:
#                 ns_server_name: "[EU/AT] FromWau's CrappyOddBall Server"
#                 ns_server_desc: Example Server configurated via FromWau/NorthstarManager
#                 ns_should_return_to_lobby: 1
#                 ns_private_match_only_host_can_change_settings: 2
#                 ns_private_match_countdown_length: 0
#                 ns_player_auth_port: 8081
# 
#     TeabagConfirmed:
#         enabled: false
#         Mods:
#             Northstar:
#                 repository: R2Northstar/Northstar
#                 last_update: '0001-01-01T00:00:00'
#                 install_dir: .
#                 file: NorthstarLauncher.exe
# 
#             PlayerVote:
#                 repository: ScureX/PlayerVote
#                 last_update: '0001-01-01T00:00:00'
#             TeabagConfirmed_Mod:
#                 repository: x3Karma/Teabag-Confirmed
#                 last_update: '0001-01-01T00:00:00'
#         config:
#             ns_startup_args_dedi.txt: +setplaylist private_match -multiple +mp_gamemode
#                 tbag -enablechathooks +setplaylistvaroverrides "custom_air_accel_pilot
#                 9000"
#             mod.json:
#                 ConVars:
#                     ns_private_match_last_map: mp_glitch
#                     ns_private_match_last_mode: tbag
#             autoexec_ns_server.cfg:
#                 ns_server_name: "[EU/AT] FromWau's TeabagConfirmed Server"
#                 ns_server_desc: Example Server configurated via FromWau/NorthstarManager
#                 ns_should_return_to_lobby: 1
#                 ns_private_match_only_host_can_change_settings: 2
#                 ns_private_match_countdown_length: 0
#                 ns_player_auth_port: 8081