on:
  push:
    branches:
    - release/*
  workflow_dispatch:
name: Release Builder  
jobs:
  builder:
    name: Compile for new Release
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2        
      - name: Setup Python  
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version fbs requests PyQt5==5.9.2
      - name: Run fbs and freeze application
        run: |
          fbs freeze
          fbs installer   
      - name: Upload Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/fbs_tutorial_appSetup.exe
          asset_name: NorthstarUpdater.exe
          tag: ${{ github.ref }}
          overwrite: true
      
