on:
  push:
    branches:
    - release/*
  workflow_dispatch:
name: Release Builder  
jobs:
  builder:
    name: compile py to exe
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2   
        
      - name: Setup Python  
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install Python dependencies
        run: python -m pip install nuitka tqdm
        
      - name: Run nuitka
        run: python -m nuitka --enable-plugin=anti-bloat --include-module=tqdm --windows-icon-from-ico=ns_icon_pink.ico NorthstarUpdater.py
      
      - name: Create Release 
        id: create_release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          file: NorthstarUpdater.exe
          asset_name: NorthstarUpdater.exe
          tag: ${{ github.ref }}
          draft: false
          prerelease: false
