on:
  push:
    branches:
    - release/*
  workflow_dispatch:
name: Release Builder  
jobs:
  builder:
    name: Compile for new Release
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2        
      - name: Setup Python  
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install Python dependencies
        run: python -m pip install nuitka tqdm
      - name: Run nuitka
        run: python -m nuitka --enable-plugin=anti-bloat --include-module=tqdm --windows-icon-from-ico=ns_icon_pink.ico NorthstarUpdater.py
      - name: Upload Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: NorthstarUpdater.exe
          asset_name: NorthstarUpdater.exe
          tag: ${{ github.ref }}
          overwrite: true
      
